### PR TITLE
Make it possible to pass options to printer

### LINKED ISSUE #11: Specify page size
Hi,
Is it possible to specify the page size of the file to print? Or somehow pass parameters to the printer function?
Maybe I've simply overlooked something in the code...

### PR DESCRIPTION
**Pull request by JuliDi**
This could serve as a starting point for allowing users to pass options to the printers. I only tested this on macOS, and it seems to work there.

There is of course a lot that can be improved, but it might be a good start.

fixes #11

### CODE REVIEW

**Comment by trembel** [comment]
What's the state of this?

**Comment by doomspork** [comment]
@talesluna @JuliDi anything we could do to help with this? I'd very much like to leverage this library but I need this capability. Happy to help however.

**Comment by JuliDi** [comment]
Not sure, there isn't really anything blocking this PR. It works as is and pends integration into a new release afaik, see https://github.com/talesluna/rust-printers/issues/11#issuecomment-1423680232

**Comment by sam-rusty** [comment]
Hey, great job. I currently have an electron app where i am using print api with options like this 
```
window.webContents.print({
    margins: { marginType: 'none' },
    pageRanges: [{ from: 1, to: 1 }],
    pageSize: {
      width: 101600, // 4 inches
      height: 152400 // 6 inches
    },
})
```
how do i pass these options when using printers::print?

**Comment by JuliDi** [comment]
Haven't used it in a while, but this is what I have in the app I made that branch for:

```rust
let mut printer: Vec<Printer> = printers::get_printers();
let printer = printer
    .iter_mut()
    .find(|p| p.system_name == *selected)
    .unwrap();
// See https://www.cups.org/doc/options.html
printer.add_option(PrinterOption::new(r#"PageSize="Custom.54x101mm""#));
printer.add_option(PrinterOption::new(r#"orientation-requested=4"#)); // landscape
                                                                        //printer.add_option(PrinterOption::new(r#"orientation-requested=3"#)); // portrait
printer.add_option(PrinterOption::new(r#"fit-to-page"#));

printer.print_file(&file);
```

**Comment by talesluna** [comment]
Thanks for contribution but this project has changed the old way with LPR commands to an CUPS implementation and this changes cannot be merged

I intend to study the possibility of printer options again as soon as possible.

Sorry for the delay in appreciating your PR

**Pull request closed without merging**
